#!/bin/bash
# deploy.sh — Mac Mini 배포 가이드
# 실제 배포는 Mac Mini에서 직접 실행

echo "📋 Mac Mini 배포 절차:"
echo ""
echo "  [전체 재배포] 코드 변경 시"
echo "     git pull origin main"
echo "     export GIT_COMMIT=\$(git rev-parse --short HEAD)"
echo "     docker compose build"
echo "     docker compose up -d"
echo ""
echo "  [순차 배포] 봇별 순서대로 재시작 (영향 최소화)"
echo "     git pull origin main"
echo "     export GIT_COMMIT=\$(git rev-parse --short HEAD)"
echo "     docker compose build"
echo "     docker compose up -d --no-deps dodol-bot-001"
echo "     docker compose up -d --no-deps dodol-bot-002"
echo "     docker compose up -d --no-deps dodol-bot-003"
echo "     docker compose up -d --no-deps dodol-bot-004"
echo ""
echo "  [신규 봇 추가] docker-compose.yml에 서비스 추가 후"
echo "     docker compose up -d --no-deps dodol-bot-005"
echo ""
echo "  [특정 봇만 재시작]"
echo "     docker compose restart dodol-bot-003"
echo ""
echo "  [버전 확인]"
echo "     docker compose logs --tail=5 | grep 'commit:'"
echo ""
echo "  [로그 확인]"
echo "     docker compose logs -f dodol-bot-003"
echo ""
echo "  [DB 백업]"
echo "     cp ~/dodol-bot/data/bot.db ~/dodol-bot/backups/bot_\$(date +%Y%m%d).db"
