app = 'dodol-bot-003'
primary_region = 'nrt'

[build]

[env]
  BOT_NUMBER = '3'

[[mounts]]
  source = 'dodol_bot_003_data'
  destination = '/app/data'
  initial_size = '1gb'

[vm]
  cpus = 1
  cpu_kind = 'shared'
  memory = '256mb'
